### ISSUE TITLE
styling tabs via css classes

### ISSUE THREAD

**Issue by roeap** [plotly/dash-core-components#327]
Hi Plotly Team,

I can't get styling of the tabs component via css classes to function properly. Without knowing much about it, a guess could be it has to do with inconsistent naming of the `selected_className` property in the Tabs and Tab component.

I placed the following css file in the assets folder.

```css
.tab-style {
  width: inherit;
  border: none;
  background: white;
  padding-top: 0;
  padding-bottom: 0;
  height: 42px;
}

.selected-tab-style {
  width: inherit;
  box-shadow: none;
  border-left: none;
  border-right: none;
  border-top: none;
  border-bottom: 2px #004A96 solid;
  background: white;
  padding-top: 0;
  padding-bottom: 0;
  height: 42px;
}
```
and used the following app to reproduce the behavior.

```python
import dash
import dash_core_components as dcc
import dash_html_components as html

TAB_STYLE = {
    'width': 'inherit',
    'border': 'none',
    'boxShadow': 'inset 0px -1px 0px 0px lightgrey',
    'background': 'white',
    'paddingTop': 0,
    'paddingBottom': 0,
    'height': '42px',
}

SELECTED_STYLE = {
    'width': 'inherit',
    'boxShadow': 'none',
    'borderLeft': 'none',
    'borderRight': 'none',
    'borderTop': 'none',
    'borderBottom': '2px #004A96 solid',
    'background': 'white',
    'paddingTop': 0,
    'paddingBottom': 0,
    'height': '42px',
}

app = dash.Dash()
app.layout = html.Div([
    dcc.Tabs(
        id='tabs-1',
        value='tab-1',
        children=[
            dcc.Tab(
                label='Tab 1',
                value='tab-1',
                style=TAB_STYLE,
                selected_style=SELECTED_STYLE,
            ),
            dcc.Tab(
                label='Tab 2',
                value='tab-2',
                style=TAB_STYLE,
                selected_style=SELECTED_STYLE,
            ),
        ]
    ),
    html.Br(),
    dcc.Tabs(
        id='tabs-2',
        value='tab-1',
        children=[
            dcc.Tab(
                label='Tab 1',
                value='tab-1',
                className='tab-style',
                selected_className='selected-tab-style',
            ),
            dcc.Tab(
                label='Tab 2',
                value='tab-2',
                className='tab-style',
                selected_className='selected-tab-style',
            ),
        ]
    )
])

app.css.config.serve_locally = True
app.scripts.config.serve_locally = True

if __name__ == '__main__':
    app.run_server(debug=True)
```

Any insight on this is greatly appreciated.
